// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKyYU3fb74kvR05GxClSoLGwsVd0vDPbI',
    appId: '1:501660129134:web:dd9590e2468f3f3fd8937f',
    messagingSenderId: '501660129134',
    projectId: 'smartschool-4044e',
    authDomain: 'smartschool-4044e.firebaseapp.com',
    storageBucket: 'smartschool-4044e.firebasestorage.app',
    measurementId: 'G-TBDHT4RNYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7btqXq8s5FD98o2buEXdfVvtC8vsT_QE',
    appId: '1:501660129134:android:177347567035d652d8937f',
    messagingSenderId: '501660129134',
    projectId: 'smartschool-4044e',
    storageBucket: 'smartschool-4044e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtTjt6EezmF95vXkqZhAoWB1T7xho-3Ow',
    appId: '1:501660129134:ios:2ec316133ef21955d8937f',
    messagingSenderId: '501660129134',
    projectId: 'smartschool-4044e',
    storageBucket: 'smartschool-4044e.firebasestorage.app',
    iosBundleId: 'com.example.smartschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtTjt6EezmF95vXkqZhAoWB1T7xho-3Ow',
    appId: '1:501660129134:ios:2ec316133ef21955d8937f',
    messagingSenderId: '501660129134',
    projectId: 'smartschool-4044e',
    storageBucket: 'smartschool-4044e.firebasestorage.app',
    iosBundleId: 'com.example.smartschool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKyYU3fb74kvR05GxClSoLGwsVd0vDPbI',
    appId: '1:501660129134:web:7a50778801f728c4d8937f',
    messagingSenderId: '501660129134',
    projectId: 'smartschool-4044e',
    authDomain: 'smartschool-4044e.firebaseapp.com',
    storageBucket: 'smartschool-4044e.firebasestorage.app',
    measurementId: 'G-FT4CQT3FP5',
  );
}
